version: '3.8'
services:
  app:
    container_name: laravel-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    depends_on:
      - laravel-db
    ports:
      - "80:80"
  laravel-db:
    container_name: laravel-db
    image: mariadb:10.7.8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
